#!/bin/bash
out=$(command ./build/day$1 < ./data/day$1e.txt)

if [ $2 ];
then
    if [ $out -eq $2 ]
    then
        echo -e "\033[0;32mSUCCESS\033[0m"
    else
        echo -e "\033[0;31mFAILURE\033[0m"
    fi
else
    echo "$out"
fi
